import { Product, Workshop, BlogPost, Testimonial } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Kantha Wrap Dress',
    category: 'dresses',
    price: 8500,
    image: 'https://picsum.photos/seed/dress-kantha/600/800',
    story: 'Born from a 1970s cotton sari discovered at a Sunday flea market, this wrap dress carries decades of stories within its threads. Hand-stitched kantha embroidery traces patterns that once adorned a grandmother\'s garment.',
    materials: ['Vintage cotton sari', 'Recycled thread', 'Antique brass hook closures'],
    isLimited: true,
    availableCount: 1,
    isNew: false,
    originalItem: 'Vintage 1970s Bengali sari',
  },
  {
    id: 'p2',
    name: 'Indigo Wrap Skirt',
    category: 'bottoms',
    price: 5400,
    image: 'https://picsum.photos/seed/skirt-indigo/600/800',
    story: 'Three discarded indigo-dyed garments found new purpose in this sculptural wrap skirt. The asymmetric hem tells the story of each individual piece, now harmoniously united.',
    materials: ['Upcycled indigo cotton', 'Organic cotton lining', 'Handmade waistband tie'],
    isLimited: false,
    availableCount: 3,
    isNew: true,
    originalItem: 'Assorted indigo cotton garments',
  },
  {
    id: 'p3',
    name: 'Vintage Silk Blouse',
    category: 'tops',
    price: 3800,
    image: 'https://picsum.photos/seed/blouse-silk/600/800',
    story: 'A collection of vintage silk scarves — each with its own origin — were carefully deconstructed and reimagined into this flowing blouse. Every panel is a different decade of silk.',
    materials: ['Vintage silk scarves (1960–1990)', 'Silk thread', 'Mother of pearl buttons'],
    isLimited: true,
    availableCount: 2,
    isNew: false,
    originalItem: 'Collection of vintage silk scarves',
  },
  {
    id: 'p4',
    name: 'Patchwork Trousers',
    category: 'bottoms',
    price: 6800,
    image: 'https://picsum.photos/seed/trousers-patch/600/800',
    story: 'Panels of denim, linen, and cotton sourced from six different garments come together in these wide-leg trousers. A meditation on contrast, texture, and second chances.',
    materials: ['Reclaimed denim', 'Vintage linen', 'Upcycled cotton', 'Adjustable waist tie'],
    isLimited: false,
    availableCount: 4,
    isNew: true,
    originalItem: 'Six assorted pre-loved garments',
  },
  {
    id: 'p5',
    name: 'Hand-Dyed Silk Scarf',
    category: 'scarves',
    price: 2100,
    image: 'https://picsum.photos/seed/scarf-silk/600/800',
    story: 'Pure silk reclaimed from damaged garments, hand-dyed using natural indigo and turmeric, creating colour gradients that no machine could replicate.',
    materials: ['Reclaimed pure silk', 'Natural indigo dye', 'Turmeric dye'],
    isLimited: false,
    availableCount: 8,
    isNew: false,
    originalItem: 'Damaged silk garments',
  },
  {
    id: 'p6',
    name: 'Upcycled Tote Bag',
    category: 'accessories',
    price: 1600,
    image: 'https://picsum.photos/seed/bag-tote/600/800',
    story: 'Heavy canvas from vintage military uniforms, combined with hand-stamped fabric scraps, makes this the most durable tote you\'ll ever own — with a conscience built in.',
    materials: ['Vintage canvas', 'Fabric scraps', 'Brass rivets', 'Natural rope handles'],
    isLimited: false,
    availableCount: 6,
    isNew: false,
    originalItem: 'Vintage canvas military uniforms',
  },
  {
    id: 'p7',
    name: 'Block Print Midi Dress',
    category: 'dresses',
    price: 7200,
    image: 'https://picsum.photos/seed/dress-block/600/800',
    story: 'A pair of oversized men\'s shirts and cotton kurta fabric found together at a textile market inspired this relaxed midi silhouette. Hand block printing adds geometric rhythm.',
    materials: ['Upcycled cotton shirts', 'Cotton kurta fabric', 'Natural block print ink'],
    isLimited: true,
    availableCount: 1,
    isNew: true,
    originalItem: 'Oversized cotton shirts + kurta fabric',
  },
  {
    id: 'p8',
    name: 'Embroidered Collar Top',
    category: 'tops',
    price: 2900,
    image: 'https://picsum.photos/seed/top-collar/600/800',
    story: 'A simple pre-loved white shirt becomes extraordinary through hours of hand embroidery using threads salvaged from old tapestries. The collar blooms with wildflower motifs.',
    materials: ['Pre-loved white cotton shirt', 'Salvaged embroidery thread', 'Handwork: 12 hours'],
    isLimited: true,
    availableCount: 2,
    isNew: false,
    originalItem: 'Pre-loved white cotton shirt',
  },
];

export const WORKSHOPS: Workshop[] = [
  {
    id: 'w1',
    title: 'Upcycling Basics',
    category: 'basics',
    date: 'July 19, 2026',
    time: '10:00 AM – 1:00 PM',
    duration: '3 hours',
    price: 1200,
    spotsLeft: 6,
    totalSpots: 10,
    description: 'Your introduction to the world of upcycling. Learn the foundational techniques to transform old garments into contemporary pieces — no prior sewing experience needed.',
    image: 'https://picsum.photos/seed/workshop-basics/600/400',
    level: 'Beginner',
    highlights: ['No experience required', 'All materials provided', 'Take home your creation', 'Refreshments included'],
  },
  {
    id: 'w2',
    title: 'Creative Repair & Mending',
    category: 'repair',
    date: 'July 26, 2026',
    time: '2:00 PM – 5:00 PM',
    duration: '3 hours',
    price: 1500,
    spotsLeft: 3,
    totalSpots: 8,
    description: 'Visible mending as an art form. Learn Japanese sashiko stitching, kantha work, and creative darning to turn tears and worn patches into beautiful design features.',
    image: 'https://picsum.photos/seed/workshop-repair/600/400',
    level: 'All Levels',
    highlights: ['Sashiko & kantha techniques', 'Bring your own worn garments', 'Certificate of completion', 'Studio materials provided'],
  },
  {
    id: 'w3',
    title: 'Sustainable Styling Masterclass',
    category: 'styling',
    date: 'August 9, 2026',
    time: '11:00 AM – 2:00 PM',
    duration: '3 hours',
    price: 2000,
    spotsLeft: 8,
    totalSpots: 12,
    description: 'A masterclass in building a capsule wardrobe from what you already own. Styling philosophy, mindful consumption, and practical techniques for creating 30 looks from 10 pieces.',
    image: 'https://picsum.photos/seed/workshop-styling/600/400',
    level: 'All Levels',
    highlights: ['Capsule wardrobe planning', 'Styling photography session', 'Digital lookbook takeaway', 'Q&A with Arpitha'],
  },
  {
    id: 'w4',
    title: 'DIY Fashion Project Day',
    category: 'diy',
    date: 'August 16, 2026',
    time: '10:00 AM – 4:00 PM',
    duration: 'Full day (6 hours)',
    price: 2800,
    spotsLeft: 5,
    totalSpots: 8,
    description: 'A full creative day at the studio. Choose your project — bag, garment, or accessory — and receive guided, hands-on mentoring from Arpitha and her team throughout.',
    image: 'https://picsum.photos/seed/workshop-diy/600/400',
    level: 'Intermediate',
    highlights: ['Choose your own project', 'Full day mentorship', 'Lunch and refreshments', 'Studio materials + tools'],
  },
  {
    id: 'w5',
    title: 'Private Workshop',
    category: 'private',
    date: 'By appointment',
    time: 'Flexible',
    duration: '2–4 hours',
    price: 5000,
    spotsLeft: 99,
    totalSpots: 99,
    description: 'A personalised session designed entirely around your goals. Perfect for birthdays, hen parties, corporate team events, or anyone wanting focused one-on-one time with Arpitha.',
    image: 'https://picsum.photos/seed/workshop-private/600/400',
    level: 'All Levels',
    highlights: ['Customised curriculum', 'Private studio access', 'Group bookings welcome', 'Date and time flexible'],
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 'b1',
    title: 'How Old Clothes Can Become New Stories',
    category: 'fashion-stories',
    excerpt: 'Every garment you have ever owned holds memory. The cotton in your first school shirt, the silk of a gifted blouse, the denim worn soft by years of wear. We explore why the most extraordinary fashion stories start with what already exists.',
    date: 'June 14, 2026',
    readTime: '5 min read',
    image: 'https://picsum.photos/seed/blog-stories/800/500',
    featured: true,
  },
  {
    id: 'b2',
    title: '5 Ways to Build a Sustainable Wardrobe Starting Today',
    category: 'sustainability',
    excerpt: 'You do not need to throw everything away and start fresh. Sustainability is a practice, not a destination. These five principles will transform how you think about the clothes already hanging in your wardrobe.',
    date: 'June 7, 2026',
    readTime: '7 min read',
    image: 'https://picsum.photos/seed/blog-wardrobe/800/500',
    featured: false,
  },
  {
    id: 'b3',
    title: 'The Beauty of Slow Fashion',
    category: 'inspiration',
    excerpt: 'Fast fashion promises everything. Slow fashion keeps its promises. In a world of endless trend cycles, we make a case for choosing fewer things, made better, that last longer and mean more.',
    date: 'May 28, 2026',
    readTime: '4 min read',
    image: 'https://picsum.photos/seed/blog-slow/800/500',
    featured: false,
  },
  {
    id: 'b4',
    title: 'Why Upcycling Is the Future of Fashion',
    category: 'sustainability',
    excerpt: 'The global fashion industry produces 92 million tonnes of textile waste each year. Upcycling does not just divert waste — it reimagines value, craft, and the relationship between maker and wearer.',
    date: 'May 20, 2026',
    readTime: '6 min read',
    image: 'https://picsum.photos/seed/blog-future/800/500',
    featured: true,
  },
  {
    id: 'b5',
    title: 'A Day in the Studio: Behind the Scenes',
    category: 'studio-diary',
    excerpt: 'Follow us through a full day at the Second Time studio in Auroville — from the morning chai ritual to the last stitch before sundown. This is where the magic lives.',
    date: 'May 12, 2026',
    readTime: '3 min read',
    image: 'https://picsum.photos/seed/blog-studio/800/500',
    featured: false,
  },
  {
    id: 'b6',
    title: 'Sashiko: The Japanese Art of Visible Mending',
    category: 'diy',
    excerpt: 'In Japan, broken things are not hidden — they are repaired with gold. Sashiko is the textile equivalent: a running stitch that transforms damage into decoration. Here is how to begin.',
    date: 'May 5, 2026',
    readTime: '8 min read',
    image: 'https://picsum.photos/seed/blog-sashiko/800/500',
    featured: false,
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 't1',
    name: 'Priya Mahadevan',
    location: 'Chennai',
    text: 'The upcycling workshop completely changed how I see my wardrobe. I brought an old sari I had been meaning to donate and left with a wrap skirt I now wear every week. Arpitha has a gift for teaching.',
    type: 'workshop',
    avatar: 'https://picsum.photos/seed/priya/80/80',
  },
  {
    id: 't2',
    name: 'Ananya Reddy',
    location: 'Bangalore',
    text: 'The Kantha Wrap Dress I ordered arrived even more beautiful than I imagined. The story card that came with it — explaining which garment it was made from — made me emotional. This is fashion with a soul.',
    type: 'shop',
    avatar: 'https://picsum.photos/seed/ananya/80/80',
  },
  {
    id: 't3',
    name: 'Shreya Krishnaswamy',
    location: 'Pondicherry',
    text: 'I brought three garments I had been holding onto but never wore — pieces with sentimental value. Arpitha transformed them into a jacket I wear constantly. It feels like wearing a family heirloom.',
    type: 'custom',
    avatar: 'https://picsum.photos/seed/shreya/80/80',
  },
];

export const STATS = [
  { value: 847, label: 'Garments Reimagined', suffix: '+' },
  { value: 124, label: 'Workshops Conducted', suffix: '' },
  { value: 3200, label: 'Community Members', suffix: '+' },
  { value: 1.2, label: 'Tonnes of Textile Saved', suffix: 'T', decimal: true },
];
